In [2]:
import pandas as pd

In [8]:
print(pd.__version__)

2.3.3

In [9]:
s = pd.Series([200, 300, 400])

In [10]:
s

0    200
1    300
2    400
dtype: int64

In [11]:
s = pd.Series([200, 400, 590], index=['a', 'b', 'c'])

In [12]:
s

a    200
b    400
c    590
dtype: int64

In [15]:
s.iloc[0]

200

In [16]:
s.loc['a']

200

In [17]:
s.shape

(3,)

In [18]:
s.size

3

In [19]:
s.dtype

dtype('int64')

In [22]:
s = pd.Series([2, 7, 7], index=[2, 5, 6])

In [23]:
s

2    2
5    7
6    7
dtype: int64

In [31]:
d = {
    "names":["ali", 'usman', 'khlaid'],
    "marks":[23, 76, 76],
    'age':[23, 23, 23]
}

In [25]:
d

{'names': ['ali', 'usman', 'khlaid'],
 'marks': [23, 76, 76],
 'age': [23, 23, 23]}

In [26]:
df = pd.DataFrame(d)

In [27]:
df

    names  marks  age
0     ali     23   23
1   usman     76   23
2  khlaid     76   23

In [29]:
df.loc[0, 'names']

'ali'

In [ ]:
df.iloc[:, 0]

0       ali
1     usman
2    khlaid
Name: names, dtype: object

In [31]:
df.names

0       ali
1     usman
2    khlaid
Name: names, dtype: object

In [32]:
df.age

0    23
1    23
2    23
Name: age, dtype: int64

In [33]:
df['names']

0       ali
1     usman
2    khlaid
Name: names, dtype: object

In [36]:
df = pd.DataFrame([[20, 40, 49], [21, 59, 38], [37, 47, 93]], columns=["sub1", "sub2", "sub3"])

In [37]:
df

   sub1  sub2  sub3
0    20    40    49
1    21    59    38
2    37    47    93

In [39]:
df.columns = ['a', 'b', 'c']

In [40]:
df

    a   b   c
0  20  40  49
1  21  59  38
2  37  47  93

In [42]:
df.index = [3, 4, 5]

In [43]:
df

    a   b   c
3  20  40  49
4  21  59  38
5  37  47  93

In [44]:
df['c']

3    49
4    38
5    93
Name: c, dtype: int64

In [45]:
df.c

3    49
4    38
5    93
Name: c, dtype: int64

In [46]:
df.iloc[:, 2]

3    49
4    38
5    93
Name: c, dtype: int64

In [5]:
df = pd.read_csv(r"datasets\students.csv")

In [6]:
df

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
...,...,...,...,...,...,...,...,...,...,...
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [7]:
df.head(4)

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0

In [8]:
df.tail(4)

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
181,S1067,Male,Lahore,BSSE,7,1.4,82.0,2.14,65.3,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [9]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [10]:
df.head(10)

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
5,S1104,Female,Karachi,BBA,4,7.6,79.2,2.46,55.4,0
6,S1032,Male,Peshawar,BBA,2,0.5,81.3,2.17,48.3,0
7,S1074,Male,Peshawar,BSCS,3,2.7,90.4,3.13,62.5,0
8,S1121,Female,Peshawar,BSCS,4,30.0,78.7,3.23,92.4,0
9,S1155,Female,Karachi,BSCS,3,15.0,79.2,3.31,79.3,0

In [11]:
df.student_id

0      S1099
1      S1179
2      S1131
3      S1024
4      S1065
       ...
179    S1103
180    S1151
181    S1067
182    S1025
183    S1175
Name: student_id, Length: 184, dtype: object

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   184 non-null    object
 1   gender       184 non-null    object
 2   city         184 non-null    object
 3   program      184 non-null    object
 4   semester     184 non-null    int64
 5   study_hours  179 non-null    float64
 6   attendance   168 non-null    float64
 7   prev_gpa     174 non-null    float64
 8   final_marks  184 non-null    float64
 9   scholarship  184 non-null    int64
dtypes: float64(4), int64(2), object(4)
memory usage: 14.5+ KB

In [13]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [17]:
df[['attendance', 'prev_gpa', 'study_hours', 'final_marks']]

     attendance  prev_gpa  study_hours  final_marks
0          87.5      1.91          8.1         68.5
1          77.4       NaN          5.2         54.4
2          96.9       NaN          4.0         68.7
3         100.0      2.84          2.5         56.8
4          87.8       NaN          7.7         68.8
..          ...       ...          ...          ...
179        68.6      3.73          5.5         56.0
180        70.1      2.37          3.5         63.5
181        82.0      2.14          1.4         65.3
182        97.8      2.35          7.9         71.5
183        75.5      2.04          6.3         57.8

[184 rows x 4 columns]

In [18]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [19]:
df.iloc[4]

student_id      S1065
gender           Male
city           Quetta
program          BSSE
semester            4
study_hours       7.7
attendance       87.8
prev_gpa          NaN
final_marks      68.8
scholarship         0
Name: 4, dtype: object

In [21]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [24]:
m = df['program'] == "BBA"

In [25]:
m

0       True
1      False
2       True
3      False
4      False
       ...
179    False
180    False
181    False
182    False
183    False
Name: program, Length: 184, dtype: bool

In [26]:
df[m]

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
5,S1104,Female,Karachi,BBA,4,7.6,79.2,2.46,55.4,0
6,S1032,Male,Peshawar,BBA,2,0.5,81.3,2.17,48.3,0
13,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
14,S1129,Female,Peshawar,BBA,8,3.6,87.9,3.79,69.0,1
16,S1148,Male,Karachi,BBA,2,3.9,NaN,2.03,75.3,0
18,S1122,Male,Karachi,BBA,8,3.6,74.8,NaN,60.4,1
35,S1128,Male,Peshawar,BBA,3,6.1,100.0,2.57,85.0,0
41,S1139,Male,Multan,BBA,4,2.5,72.5,2.89,45.1,0
43,S1097,Male,Karachi,BBA,2,12.4,81.3,2.94,65.6,0
46,S1109,Female,Peshawar,BBA,1,2.3,100.0,2.88,45.1,0
54,S1126,Male,Lahore,BBA,5,8.0,74.1,2.56,70.8,0
55,S1005,Female,Karachi,BBA,7,2.1,NaN,2.59,61.1,0
56,S1017,Male,Quetta,BBA,7,9.1,89.6,2.43,83.9,0
58,S1120,Female,Islamabad,BBA,8,7.0,89.8,3.26,68.2,1
59,S1143,Male,Karachi,BBA,6,NaN,78.7,2.66,67.0,0
61,S1125,Male,Lahore,BBA,8,7.7,84.2,3.11,65.2,1
66,S1163,male,Karachi,BBA,4,7.9,78.8,NaN,67.3,1
69,S1064,Female,Karachi,BBA,3,9.3,76.0,2.80,60.9,0
77,S1117,Female,Quetta,BBA,8,19.3,77.1,2.84,80.9,0
80,S1173,Female,Karachi,BBA,7,3.6,54.2,2.59,42.1,1
83,S1079,Female,Karachi,BBA,3,10.4,88.5,2.58,74.5,1
84,S1106,Male,Peshawar,BBA,2,4.7,71.0,2.50,56.1,0
85,S1111,Male,Peshawar,BBA,3,6.5,99.2,NaN,77.4,1
88,S1039,Female,Lahore,BBA,4,14.1,NaN,3.10,83.0,0
89,S1119,Female,KARACHI,BBA,5,18.5,63.5,3.26,85.5,1
90,S1077,Female,Peshawar,BBA,7,9.8,71.7,3.19,70.9,0
91,S1116,Female,Multan,BBA,6,4.9,83.3,2.87,61.2,0
103,S1020,Female,Islamabad,BBA,4,5.7,78.4,2.67,66.4,0
105,S1116,Female,Multan,BBA,6,4.9,83.3,2.87,61.2,0
128,S1030,female,Islamabad,BBA,6,1.3,83.6,3.10,56.1,0
136,S1100,Female,Peshawar,BBA,5,14.4,99.3,2.81,86.0,0
140,S1035,Male,Islamabad,BBA,4,8.1,89.6,3.25,77.7,1
142,S1176,Male,Islamabad,BBA,2,17.2,82.2,3.03,78.0,0
146,S1118,Male,Islamabad,BBA,7,19.9,65.2,2.44,88.4,0
147,S1144,Male,Quetta,BBA,4,3.7,68.2,2.68,53.0,1
151,S1087,Male,Peshawar,BBA,4,6.6,99.7,2.46,62.8,0
152,S1137,Male,Islamabad,BBA,6,7.5,90.4,3.04,70.1,1
154,S1038,male,Multan,BBA,6,10.9,90.0,2.73,64.4,1
167,S1135,Male,Lahore,BBA,1,6.3,88.2,3.34,72.5,1
171,S1136,Female,Lahore,BBA,5,5.9,68.8,2.93,64.8,1
173,S1110,Male,Quetta,BBA,4,1.0,75.0,3.86,51.2,1
174,S1089,Male,Peshawar,BBA,8,18.9,86.9,3.21,91.8,0
176,S1023,Female,Peshawar,BBA,2,5.6,99.8,1.85,67.4,0

In [29]:
df[df['city'] == "Peshawar"]

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
6,S1032,Male,Peshawar,BBA,2,0.5,81.3,2.17,48.3,0
7,S1074,Male,Peshawar,BSCS,3,2.7,90.4,3.13,62.5,0
8,S1121,Female,Peshawar,BSCS,4,30.0,78.7,3.23,92.4,0
14,S1129,Female,Peshawar,BBA,8,3.6,87.9,3.79,69.0,1
19,S1091,Female,Peshawar,BSEE,6,6.6,87.3,3.75,72.1,1
24,S1080,Female,Peshawar,BSEE,5,8.1,70.5,3.21,63.3,1
25,S1088,Male,Peshawar,BSCS,8,6.1,83.8,2.91,80.0,1
26,S1169,Female,Peshawar,BSCS,8,8.0,82.4,3.11,59.6,0
27,S1078,Male,Peshawar,BSSE,4,14.1,75.5,3.30,76.0,1
28,S1036,Male,Peshawar,BSSE,8,8.3,82.0,2.89,63.8,0
34,S1102,Male,Peshawar,BSEE,6,5.0,79.6,3.43,62.6,1
35,S1128,Male,Peshawar,BBA,3,6.1,100.0,2.57,85.0,0
40,S1011,Female,Peshawar,BSCS,4,15.0,87.3,2.12,71.2,0
46,S1109,Female,Peshawar,BBA,1,2.3,100.0,2.88,45.1,0
47,S1037,Male,Peshawar,BSCS,5,8.3,86.1,2.14,65.9,0
48,S1113,Male,Peshawar,BSCS,6,8.4,80.2,2.95,68.7,0
49,S1028,Male,Peshawar,BSCS,8,6.3,91.2,2.48,62.3,0
60,S1049,Male,Peshawar,BSEE,6,2.7,78.7,2.39,55.5,1
62,S1046,Male,Peshawar,BSCS,7,0.5,69.5,3.96,57.4,0
64,S1171,Male,Peshawar,BSSE,4,1.2,82.0,3.55,52.9,0
65,S1156,Male,Peshawar,BSCS,1,5.0,79.8,2.76,65.6,0
67,S1085,Male,Peshawar,BSSE,1,6.4,100.0,2.95,80.6,0
68,S1062,Male,Peshawar,BSCS,8,NaN,NaN,3.39,63.0,1
70,S1026,Male,Peshawar,BSSE,2,7.2,80.7,2.85,77.5,1
74,S1160,Male,Peshawar,BSEE,5,5.3,NaN,1.37,53.6,0
75,S1007,Female,Peshawar,BSSE,8,15.8,69.5,2.96,84.8,0
79,S1154,Male,Peshawar,BSCS,6,15.6,NaN,3.24,75.6,1
82,S1086,Female,Peshawar,BSEE,1,2.5,65.5,3.08,62.5,0
84,S1106,Male,Peshawar,BBA,2,4.7,71.0,2.50,56.1,0
85,S1111,Male,Peshawar,BBA,3,6.5,99.2,NaN,77.4,1
90,S1077,Female,Peshawar,BBA,7,9.8,71.7,3.19,70.9,0
94,S1090,Male,Peshawar,BSCS,6,6.4,83.4,3.24,73.5,1
97,S1132,Female,Peshawar,BSSE,4,7.7,95.6,3.56,82.4,0
100,S1059,male,Peshawar,BSEE,5,0.6,82.4,2.42,45.5,0
101,S1015,Male,Peshawar,BSCS,1,5.1,90.8,2.07,56.8,0
104,S1014,Male,Peshawar,BSCS,3,0.9,84.8,2.76,59.8,0
107,S1009,Male,Peshawar,BSEE,2,3.9,77.1,3.71,68.4,1
111,S1012,Female,Peshawar,BSCS,7,0.5,87.6,2.25,48.5,0
114,S1058,Male,Peshawar,BSCS,6,5.9,55.8,2.51,58.5,0
116,S1138,Female,Peshawar,BSCS,7,2.5,65.7,2.17,38.1,0
118,S1018,Female,Peshawar,BSCS,1,10.2,65.1,NaN,71.4,1
119,S1050,Male,Peshawar,BSSE,4,12.6,78.0,3.72,78.0,0
125,S1073,Male,Peshawar,BSSE,8,6.4,93.7,3.61,71.2,1
126,S1101,Female,Peshawar,BSCS,8,5.8,81.1,2.04,62.4,0
136,S1100,Female,Peshawar,BBA,5,14.4,99.3,2.81,86.0,0
149,S1083,Male,Peshawar,BSCS,5,18.2,79.6,2.28,90.4,0
151,S1087,Male,Peshawar,BBA,4,6.6,99.7,2.46,62.8,0
161,S1044,Female,Peshawar,BSEE,7,11.9,76.0,2.76,70.8,0
170,S1167,Female,Peshawar,BSEE,4,8.9,97.5,3.91,72.7,1
174,S1089,Male,Peshawar,BBA,8,18.9,86.9,3.21,91.8,0
176,S1023,Female,Peshawar,BBA,2,5.6,99.8,1.85,67.4,0
178,S1092,Male,Peshawar,BSSE,4,2.5,NaN,3.60,60.9,0
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
180,S1151,Female,Peshawar,BSSE,6,3.5,70.1,2.37,63.5,0
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0

In [32]:
sdf = pd.DataFrame(d)

In [33]:
sdf

    names  marks  age
0     ali     23   23
1   usman     76   23
2  khlaid     76   23

In [37]:
sdf[sdf['marks'] > 50]

    names  marks  age
1   usman     76   23
2  khlaid     76   23

In [39]:
sdf

    names  marks  age
0     ali     23   23
1   usman     76   23
2  khlaid     76   23

In [40]:
sdf[[True, False, True]]

    names  marks  age
0     ali     23   23
2  khlaid     76   23

In [42]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,Lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [44]:
df[df['study_hours'] > 4]

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,Quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,Karachi,BSSE,7,5.2,77.4,NaN,54.4,0
4,S1065,Male,Quetta,BSSE,4,7.7,87.8,NaN,68.8,0
5,S1104,Female,Karachi,BBA,4,7.6,79.2,2.46,55.4,0
8,S1121,Female,Peshawar,BSCS,4,30.0,78.7,3.23,92.4,0
...,...,...,...,...,...,...,...,...,...,...
176,S1023,Female,Peshawar,BBA,2,5.6,99.8,1.85,67.4,0
177,S1142,Female,Lahore,BSEE,8,4.6,99.8,2.99,70.3,0
179,S1103,Female,Peshawar,BSCS,4,5.5,68.6,3.73,56.0,1
182,S1025,Male,Peshawar,BSEE,2,7.9,97.8,2.35,71.5,0
183,S1175,Male,Karachi,BSCS,1,6.3,75.5,2.04,57.8,0

In [46]:
df['program'].unique()

array(['BBA', 'BSSE', 'BSCS', 'BSEE'], dtype=object)

In [47]:
df['city'].unique()

array(['Quetta', 'Karachi', 'Lahore', 'PESHAWAR', 'Peshawar', 'KARACHI',
       'Multan', 'Islamabad'], dtype=object)

In [51]:
df[df['city'] == "PESHAWAR"]

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
3,S1024,Female,PESHAWAR,BSCS,3,2.5,100.0,2.84,56.8,0
30,S1158,Female,PESHAWAR,BSCS,3,5.6,100.0,2.35,73.0,1
120,S1149,Male,PESHAWAR,BSCS,3,5.4,77.7,2.54,48.2,0

In [56]:
df['city'] = df['city'].str.lower()

In [57]:
df['city'].unique()

array(['quetta', 'karachi', 'lahore', 'peshawar', 'multan', 'islamabad'],
      dtype=object)

In [58]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,Female,quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,Female,karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,Female,lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,Female,peshawar,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,Male,quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [60]:
df['gender'].unique()

array(['Female', 'Male', 'male', 'female'], dtype=object)

In [63]:
df['gender'] = df['gender'].str.lower()

In [64]:
df['gender'].unique()

array(['female', 'male'], dtype=object)

In [66]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,female,quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,female,karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,female,lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,female,peshawar,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,male,quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [70]:
df[df['city'] == "quetta"][['student_id', 'city']]

    student_id    city
0        S1099  quetta
4        S1065  quetta
13       S1099  quetta
22       S1146  quetta
31       S1013  quetta
32       S1114  quetta
36       S1098  quetta
53       S1060  quetta
56       S1017  quetta
77       S1117  quetta
106      S1076  quetta
110      S1124  quetta
123      S1081  quetta
130      S1033  quetta
132      S1153  quetta
133      S1162  quetta
143      S1071  quetta
147      S1144  quetta
148      S1001  quetta
164      S1055  quetta
166      S1000  quetta
173      S1110  quetta

In [72]:
df.head(10)

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,female,quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,female,karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,female,lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,female,peshawar,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,male,quetta,BSSE,4,7.7,87.8,NaN,68.8,0
5,S1104,female,karachi,BBA,4,7.6,79.2,2.46,55.4,0
6,S1032,male,peshawar,BBA,2,0.5,81.3,2.17,48.3,0
7,S1074,male,peshawar,BSCS,3,2.7,90.4,3.13,62.5,0
8,S1121,female,peshawar,BSCS,4,30.0,78.7,3.23,92.4,0
9,S1155,female,karachi,BSCS,3,15.0,79.2,3.31,79.3,0

In [75]:
df[['student_id', 'final_marks']][df['scholarship'] == 1]

    student_id  final_marks
10       S1141         54.4
11       S1168         67.7
12       S1045         42.7
14       S1129         69.0
17       S1166         64.0
..         ...          ...
171      S1136         64.8
172      S1042         49.9
173      S1110         51.2
175      S1072         65.1
179      S1103         56.0

[78 rows x 2 columns]

In [76]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship
0,S1099,female,quetta,BBA,1,8.1,87.5,1.91,68.5,0
1,S1179,female,karachi,BSSE,7,5.2,77.4,NaN,54.4,0
2,S1131,female,lahore,BBA,7,4.0,96.9,NaN,68.7,0
3,S1024,female,peshawar,BSCS,3,2.5,100.0,2.84,56.8,0
4,S1065,male,quetta,BSSE,4,7.7,87.8,NaN,68.8,0

In [79]:
df[df['scholarship'] == 1][['student_id', 'final_marks']]

    student_id  final_marks
10       S1141         54.4
11       S1168         67.7
12       S1045         42.7
14       S1129         69.0
17       S1166         64.0
..         ...          ...
171      S1136         64.8
172      S1042         49.9
173      S1110         51.2
175      S1072         65.1
179      S1103         56.0

[78 rows x 2 columns]

In [80]:
df.shape

(184, 10)

In [81]:
import numpy as np

In [88]:
arr = np.arange(184)

In [89]:
df["range"] = arr

In [90]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,range
0,S1099,female,quetta,BBA,1,8.1,87.5,1.91,68.5,0,0
1,S1179,female,karachi,BSSE,7,5.2,77.4,NaN,54.4,0,1
2,S1131,female,lahore,BBA,7,4.0,96.9,NaN,68.7,0,2
3,S1024,female,peshawar,BSCS,3,2.5,100.0,2.84,56.8,0,3
4,S1065,male,quetta,BSSE,4,7.7,87.8,NaN,68.8,0,4

In [92]:
df['sh_att'] = df['study_hours'] + df['attendance']

In [93]:
df.head()

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,range,sh_att
0,S1099,female,quetta,BBA,1,8.1,87.5,1.91,68.5,0,0,95.6
1,S1179,female,karachi,BSSE,7,5.2,77.4,NaN,54.4,0,1,82.6
2,S1131,female,lahore,BBA,7,4.0,96.9,NaN,68.7,0,2,100.9
3,S1024,female,peshawar,BSCS,3,2.5,100.0,2.84,56.8,0,3,102.5
4,S1065,male,quetta,BSSE,4,7.7,87.8,NaN,68.8,0,4,95.5

In [94]:
df.describe()

,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,range,sh_att
count,184.000000,179.000000,168.000000,174.000000,184.000000,184.000000,184.000000,164.000000
mean,4.777174,7.256983,82.155357,2.839655,65.119565,0.423913,91.500000,89.725610
std,2.285454,4.888808,10.498998,0.582331,11.508669,0.495525,53.260367,11.314113
min,1.000000,0.500000,54.200000,1.370000,32.100000,0.000000,0.000000,57.800000
25%,3.000000,3.650000,76.000000,2.460000,58.175000,0.000000,45.750000,83.075000
50%,5.000000,6.400000,82.700000,2.875000,65.700000,0.000000,91.500000,90.550000
75%,7.000000,8.850000,89.400000,3.257500,72.725000,1.000000,137.250000,97.550000
max,8.000000,30.000000,100.000000,4.000000,92.400000,1.000000,183.000000,113.700000

In [99]:
df['study_hours'].mean() + df['study_hours'].std()

12.145791124915334

In [100]:
df['study_hours'].mean() - df['study_hours'].std()

2.3681753555315934

In [106]:
df[(df['study_hours'] >2.368) & (df['study_hours'] < 12.145)]

,student_id,gender,city,program,semester,study_hours,attendance,prev_gpa,final_marks,scholarship,range,sh_att
0,S1099,female,quetta,BBA,1,8.1,87.5,1.91,68.5,0,0,95.6
1,S1179,female,karachi,BSSE,7,5.2,77.4,NaN,54.4,0,1,82.6
2,S1131,female,lahore,BBA,7,4.0,96.9,NaN,68.7,0,2,100.9
3,S1024,female,peshawar,BSCS,3,2.5,100.0,2.84,56.8,0,3,102.5
4,S1065,male,quetta,BSSE,4,7.7,87.8,NaN,68.8,0,4,95.5
...,...,...,...,...,...,...,...,...,...,...,...,...
178,S1092,male,peshawar,BSSE,4,2.5,NaN,3.60,60.9,0,178,NaN
179,S1103,female,peshawar,BSCS,4,5.5,68.6,3.73,56.0,1,179,74.1
180,S1151,female,peshawar,BSSE,6,3.5,70.1,2.37,63.5,0,180,73.6
182,S1025,male,peshawar,BSEE,2,7.9,97.8,2.35,71.5,0,182,105.7
183,S1175,male,karachi,BSCS,1,6.3,75.5,2.04,57.8,0,183,81.8

In [107]:
135/184 * 100

73.36956521739131